### PR TITLE
PR for capstone project of Ruby

### PR DESCRIPTION
**Pull request by ozovalihasan**
For this project, a bot is built. By the help of this bot, tic-tac-toe game is played on Slack

- All necessary classes created or included.
- All tests are done. Some methods couldn't be tested because they need a connection between server and Slack. So, these methods weren't tested.
- The setup part and other parts are written with details in the readme file.
- I worked alone.

### CODE REVIEW

**Comment by ozovalihasan** [comment]
Following changes are done;

- Some methods' visibility changed as private. Any accessors aren't added because the app working properly without them.
- The test section is added to the readme file.
- All steps to setup the app are shown in the videos.
- All gems are written to Gemfile.

**Comment by kubilaycaglayan** [comment]
## Dear TSE,

### As Hasan's mentor, I want to congratulate him on his great efforts. 👏 
It seems like a bit more work for the TSE too, but **let's learn from this great project altogether and give a hand **to** Hasan **to** push him **to** achieve mastery level on Ruby module**. 💯 🥇 

You can reach out to me trough slack with my name.
Good luck Hasan, GREAT PROJECT!
## With all my respect...

**Comment by ozovalihasan** [comment]
Thanks, @kubilaycaglayan for your feedback.

**Comment by ozovalihasan** [comment]
The following changes are done;

- Tests are added if it is possible to test methods.
- The Readme file is arranged to be more clear.
- Events class, events.rb and events_spec files are deleted to make the code more simple.

**Pull request merged**
